### ISSUE TITLE
0.3.5.7 install failure on ubuntu

### ISSUE THREAD

**Issue by spgarbet** [yesodweb/haskell-xss-sanitize#17]
garbetsp@biostat1427:~/Projects$ cabal install xss-sanitize
Resolving dependencies...
Downloading xss-sanitize-0.3.5.7...
Failed to install xss-sanitize-0.3.5.7
Build log ( /home/garbetsp/.cabal/logs/xss-sanitize-0.3.5.7.log ):
cabal: /home/garbetsp/.cabal/logs/xss-sanitize-0.3.5.7.log: does not exist

I tried a direct download from git and this fails as well. It creates no log and aborts on install. Tried the earlier 0.3.5.6 release and got the same result.

**Comment by 4X3L** [comment]
+1 Also on Fedora 25

**Comment by spgarbet** [comment]
I got it to install. It seems to be some naming issue with the repo switchover. Somehow the "haskell-xss-sanitize" is being reported as the name of the library, and then it fails to find xss-sanitize. I renamed my local directory and tarballed it and it installs.

**Comment by joeyh** [comment]
+1 also on Windows :(

**Comment by joeyh** [comment]
Earlier had 0.3.5.7 installed on the same system, so something exterior to the package must have broken it.

The tarball on hackage unpacks into xss-sanitize-0.3.5.7, which seems fine. @spgarbet How did you rename the local directory?

**Comment by joeyh** [comment]
0.3.5.6 also fails the same way

**Comment by andreasabel** [comment]
Stale issue? Close?
