### ISSUE TITLE
filterTags escapes HTML entities because of TagSoup's defaults

### ISSUE THREAD

**Issue by Skyfold** [yesodweb/haskell-xss-sanitize#26]
``` Haskell
*Text.HTML.SanitizeXSS> filterTags safeTags "text&nbsp;more text"
"text&amp;nbsp;more text"
```
This would display as "text &nbspmore text" instead of "text more text".

If you add `optEscape = id` to the `renderOptions` then TagSoup will stop trying to escape &"<>

``` Haskell
*Text.HTML.SanitizeXSS> filterTags safeTags "text&nbsp;more text"
"text&nbsp;more text"
```

If you are ok with this fix, I'll create a pull request with my changes.

**Comment by snoyberg** [comment]
Yes, that sounds reasonable.
