### ISSUE TITLE
Support text-2.0

### ISSUE THREAD

**Issue by andreasabel** [yesodweb/haskell-xss-sanitize#28]
Currently, `text-2.0` is excluded by constraint `text < 2`.

**Comment by snoyberg** [comment]
Have you checked if it's compatible with `text` 2? If so, a PR relaxing the bound is welcome. I'm personally not using text 2 yet.

**Comment by andreasabel** [comment]
Ok, I checked build and test with `text-2.0`, and there were no errors.  
I went ahead with a revision: https://hackage.haskell.org/package/xss-sanitize-0.3.7/revisions/
I'll submit a PR with the relaxed bound, but there is no need to release this.
