### ISSUE TITLE
Issue with style details still being included

### ISSUE THREAD

**Issue by parthshah31** [yesodweb/haskell-xss-sanitize#30]
`sanitizeBalance` sometimes still includes the content within the style tag.

Here's a minimum reproducible example that shows the issue:
```
λ> sanitizeBalance "<!DOCTYPE><html><style>html{width:100%;max-width:100%}</style></html></DOCTYPE>"
"html{width:100%;max-width:100%}"
```

This should just return "" and a simple example like this works:
```
λ> sanitizeBalance "<style>html{width:100%}</style>"

```

**Comment by snoyberg** [comment]
PR welcome to address this.

**Comment by parthshah31** [comment]
Actually fixed. Updated version. Was solved by @tysonzero
